apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
  type: Opaque
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: bXktdXNlcg==
  KC_BOOTSTRAP_ADMIN_PASSWORD: bXktcGFzc3dvcmQ=
  POSTGRES_USER: a2V5Y2xvYWs=
  POSTGRES_PASSWORD: a2V5Y2xvYWs=
  POSTGRES_DB: a2V5Y2xvYWs=