apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_PASSWORD: "change-me-admin-password"
  KC_DB_PASSWORD: "change-me-db-password"