apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    root_url = http://192.168.88.120:32000/

    [auth.generic_oauth]
    enabled = true
    name = Keycloak
    allow_sign_up = true
    client_id = grafana
    client_secret = D9YDa6yFK2Dk2YnzjYZkOzg2VjWmHcwe
    scopes = openid email profile
    auth_url = http://192.168.88.121:32100/realms/grafana/protocol/openid-connect/auth
    token_url = http://192.168.88.121:32100/realms/grafana/protocol/openid-connect/token
    api_url = http://192.168.88.121:32100/realms/grafana/protocol/openid-connect/userinfo
    role_attribute_path = contains(realm_access.roles[*], 'admin') && 'Admin' || 'Viewer'
    login_attribute_path = preferred_username
    name_attribute_path = name
    email_attribute_path = email
    verbose_logging = true

