apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: monitoring
  type: Opaque
data:
  username: bXktdXNlcg==
  password: bXktcGFzc3dvcmQ=
  image: Z3JhZmFuYS9ncmFmYW5hOmxhdGVzdAo=
  mountPath: L2V0Yy9ncmFmYW5hL2dyYWZhbmEuaW5pCg==
  subPath: Z3JhZmFuYS5pbmk=