apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    name: gitlab
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32200
    - name: ssh
      port: 22
      targetPort: ssh
  selector:
    name: gitlab
